# spring:
#     datasource:
#         url: jdbc:mysql://${IP:localhost}:${PORT:3306}/${DATABASE:gestion-consultas-externas}
#         username: root
#         password: admin
    # jpa:
    #     hibernate:
    #         ddl-auto: update
    #     properties:
    #         hibernate:
    #             dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#         show-sql: true
# server:
#   port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${HOSTNAME:localhost}